# Generated by Django 5.0.6 on 2024-08-07 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='carrusel')),
                ('fecha', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
