# Generated by Django 5.0.6 on 2024-08-07 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Asignacion_Ciclo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asistencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("presente", models.BooleanField(default=False)),
                (
                    "asignacion_ciclo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Asignacion_Ciclo.asignacionciclo",
                    ),
                ),
            ],
        ),
    ]
