# Generated by Django 5.0.6 on 2024-08-15 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Asignacion_Ciclo", "0001_initial"),
        ("Persona", "0002_remove_alumna_grado"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="asignacionciclo",
            unique_together={("alumna", "year")},
        ),
    ]
