# Generated by Django 5.0.6 on 2024-09-20 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Asignacion_Ciclo", "0002_alter_asignacionciclo_unique_together"),
        ("Curso", "0002_curso_estado_grado_estado"),
        ("Persona", "0004_alumna_estado"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="asignacionciclo",
            unique_together={("alumna", "grado", "year")},
        ),
    ]
