# Generated by Django 5.0.6 on 2024-10-20 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Asignacion_Ciclo", "0003_alter_asignacionciclo_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promocion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("año", models.IntegerField()),
                ("aprobado", models.BooleanField()),
                (
                    "asignacion_ciclo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Asignacion_Ciclo.asignacionciclo",
                    ),
                ),
            ],
        ),
    ]
