# Generated by Django 5.0.6 on 2024-09-06 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Persona", "0002_remove_alumna_grado"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contacto",
            name="persona",
        ),
        migrations.RemoveField(
            model_name="contacto",
            name="user",
        ),
        migrations.AddField(
            model_name="contacto",
            name="apellido",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contacto",
            name="nombre",
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contacto",
            name="alumna",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="Persona.alumna",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contacto",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="contacto",
            name="parentesco",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="contacto",
            name="telefono",
            field=models.CharField(max_length=15),
        ),
    ]
