# Generated by Django 5.0.6 on 2024-09-20 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Persona", "0003_remove_contacto_persona_remove_contacto_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alumna",
            name="estado",
            field=models.BooleanField(default=True),
        ),
    ]
