# Generated by Django 5.0.6 on 2024-09-05 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Curso", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="estado",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="grado",
            name="estado",
            field=models.BooleanField(default=True),
        ),
    ]
