# Generated by Django 5.0.6 on 2024-08-07 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rol", models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.RemoveField(
            model_name="user",
            name="compras",
        ),
        migrations.RemoveField(
            model_name="user",
            name="devoluciones",
        ),
        migrations.RemoveField(
            model_name="user",
            name="dir",
        ),
        migrations.RemoveField(
            model_name="user",
            name="dir2",
        ),
        migrations.RemoveField(
            model_name="user",
            name="rol",
        ),
        migrations.RemoveField(
            model_name="user",
            name="tel",
        ),
        migrations.RemoveField(
            model_name="user",
            name="tipo",
        ),
        migrations.RemoveField(
            model_name="user",
            name="token",
        ),
        migrations.RemoveField(
            model_name="user",
            name="total_compras",
        ),
        migrations.RemoveField(
            model_name="user",
            name="total_devoluciones",
        ),
        migrations.AddField(
            model_name="user",
            name="id_ciclo",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="telefono",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="user",
            name="estado",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="id_rol",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.rol",
            ),
        ),
    ]
