# Generated by Django 5.0.6 on 2024-08-07 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_rol_alter_user_options_remove_user_compras_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="estado",
        ),
    ]
