# Generated by Django 5.0.6 on 2024-09-06 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Actividad", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="actividad",
            name="estado",
            field=models.IntegerField(
                choices=[(1, "Activa"), (0, "Inactiva")], default=1
            ),
        ),
    ]
